EStudyBase/ViewModels/CreateContentViewModel.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class CreateContentViewModel
    {
        public int KeywordId { get; set; }

        [Required(ErrorMessage = " ")]
        [Display(Name = "Dil")]
        public int LanguageId { get; set; }
        public IEnumerable<SelectListItem> Languages { get; set; }

        [Required(ErrorMessage = " ")]
        [Display(Name = "Kategori")]
        public int ContentCategoryId { get; set; }
        public IEnumerable<SelectListItem> ContentCategories { get; set; }

        [Required(ErrorMessage = " ")]
        [Display(Name = "Açıklama")]
        public string Description { get; set; }

        [Display(Name = "Web adresi")]
        public string Url { get; set; }

        public ContentType ContentType { get; set; }

        public HttpPostedFileBase PostedFile { get; set; }
    }
}

EStudyBase/ViewModels/KeywordTagSelectionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class KeywordTagSelectionViewModel
    {
        public int KeywordId { get; set; }
        [DisplayName("#Tag")]
        public List<Tag> Tags { get; set; }
        [Required(ErrorMessage = " ")]
        public Int32[] SelectedTags { get; set; }
    }
}

EStudyBase/ViewModels/UserRoleSelectionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EStudyBase.ViewModels
{
    public class UserRoleSelectionViewModel
    {
        public int UserId { get; set; }

        [Display(Name = "Kullanıcı Adı")]
        public string UserName { get; set; }

        [Display(Name = "Rol")]
        public string UserRole { get; set; }
    }
}

EStudyBase/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using Datatables.Mvc;
using EStudyBase.Attributes;
using EStudyBase.Filters;
using EStudyBase.Models;
using EStudyBase.ViewModels;
using WebMatrix.WebData;

namespace EStudyBase.Controllers
{
    [InitializeSimpleMembership]
    [AjaxAuthorize(Roles = "Admin")]
    public class ManagementController : Controller
    {
        private readonly EStudyBaseContext _context = new EStudyBaseContext();
        private const string UploadFilePath = "/UploadFiles";

        public ActionResult KeywordList()
        {
            return View();
        }

        [HttpPost]
        public ActionResult KeywordList(DataTable dataTable, string userName = "")
        {
            var isSearchEmpty = string.IsNullOrWhiteSpace(dataTable.sSearch);
            
            //...
            // User portfolio
            var createUserId = WebSecurity.GetUserId(userName);
            
            var totalCount =
                _context
                .Keywords
                .Count(p => (p.Definition.ToLower().Contains(dataTable.sSearch.ToLower()) || isSearchEmpty) && (createUserId == -1 || p.CreateUserId == createUserId));

            //...
            // Where clause
            var keywordList = _context.Keywords
                .Include("Language")
                .Include("CreateUser")
                .Where(p => (p.Definition.ToLower().Contains(dataTable.sSearch.ToLower()) || isSearchEmpty) && (createUserId == -1 || p.CreateUserId == createUserId));

            //...
            // Order by clause
            var sortColumn = HttpContext.Request.Form["iSortCol_0"];
            var sortDirection = HttpContext.Request.Form["sSortDir_0"];
            switch (sortColumn)
            {
                case "0":
                    keywordList = sortDirection.Equals("asc")
                                      ? keywordList.OrderBy(p => p.KeywordId)
                                      : keywordList.OrderByDescending(p => p.KeywordId);
                    break;
                case "1":
                    keywordList = sortDirection.Equals("asc")
                                      ? keywordList.OrderBy(p => p.Definition)
                                      : keywordList.OrderByDescending(p => p.Definition);
                    break;
                case "2":
                    keywordList = sortDirection.Equals("asc")
                                      ? keywordList.OrderBy(p => p.LanguageId)
                                      : keywordList.OrderByDescending(p => p.LanguageId);
                    break;
                case "3":
                    keywordList = sortDirection.Equals("asc")
                                      ? keywordList.OrderBy(p => p.CreateUserId)
                                      : keywordList.OrderByDescending(p => p.CreateUserId);
                    break;
                default:
                    keywordList = sortDirection.Equals("asc")
                                      ? keywordList.OrderBy(p => p.CreateDate)
                                      : keywordList.OrderByDescending(p => p.CreateDate);
                    break;
            }

            //...
            // Filtering
            keywordList = keywordList
                .Skip(dataTable.iDisplayStart)
                .Take(dataTable.iDisplayLength);

            var resultTable = new List<DataTableRow>();
            foreach (var keyword in keywordList)
            {
                var operations = new StringBuilder();
                operations.Append("<table>");
                operations.Append("<tr>");

                operations.Append(
                    string.Format(
                        @"<td>
                              <a href='/Management/KeywordContentList?keywordId={0}' target='_blank'>İçerikler</a>
                         </td>",
                        keyword.KeywordId));

                operations.Append(
                    string.Format(
                        @"<td>
                              <a target='_blank' href='/Management/KeywordTagSelection?KeywordId={0}'>Tag Ekle</a>
                         </td>", keyword.KeywordId));

                operations.Append(
                    string.Format(
                        @"<td>
                              <a target='_blank' href='/Management/CreateContent?KeywordId={0}'>İçerik Ekle</a>
                         </td>", keyword.KeywordId));

                operations.Append(
                    string.Format(
                        @"<td>
                              <input type='checkbox' title='Onayla' data-toggle='tooltip' data-keyword-id='{0}' onclick='ToggleKeywordActivation(this);' {1} />
                        </td>",
                        keyword.KeywordId, keyword.Approved ? "checked" : ""));

                operations.Append(
                    string.Format(
                        @"<td>
                               <div class='icon-remove-sign' title='Sil' data-toggle='tooltip' style='cursor:pointer;' data-keyword-id='{0}' onclick='DeleteKeyword(this);'></div>
                          </td>", keyword.KeywordId));
                operations.Append("</tr>");
                operations.Append("</table>");

                var row = new DataTableRow
                    {
                        keyword.KeywordId.ToString(CultureInfo.InvariantCulture),
                        keyword.Definition,
                        keyword.Language.Definition,
                        keyword.CreateUser == null ? "Anonym" : keyword.CreateUser.UserName,
                        String.Format("{0:d/M/yyyy HH:mm}", keyword.CreateDate),
                        operations.ToString()
                    };
                resultTable.Add(row);
            }
            

            return new DataTableResultExt(dataTable, totalCount, totalCount, resultTable);
        }

        public ActionResult ToggleKeywordActivation()
        {
            var request = HttpContext.Request;
            try
            {
                int keywordId = Convert.ToInt32(request.Form["KeywordId"]);
                bool approve = Convert.ToBoolean(request.Form["Approve"]);
                
                var keyword = _context.Keywords.FirstOrDefault(p => p.KeywordId == keywordId);
                if (keyword != null)
                    keyword.Approved = approve;

                _context.SaveChanges();

                return
                    Json(
                        new
                            {
                                Result = true,
                                ResultMessage = approve ? "Başlık aktifleştirildi." : "Başlık pasifleştirildi"
                            },
                        JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return
                    Json(new {Result = false, ResultMessage = "Başlığın aktiflik durumu değiştirilirken hata oluştu!"},
                         JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult DeleteKeyword()
        {
            var request = HttpContext.Request;
            try
            {
                int keywordId = Convert.ToInt32(request.Form["KeywordId"]);

                var keyword = _context.Keywords.FirstOrDefault(p => p.KeywordId == keywordId);
                if (keyword != null)
                {
                    //...
                    // Remove keyword
                    _context.Keywords.Remove(keyword);

                    //...
                    // Remove shares
                    var shares = _context.Contents.Where(p => p.KeywordId == keyword.KeywordId);
                    foreach (var share in shares)
                    {
                        _context.Contents.Remove(share);
                    }

                    _context.SaveChanges();

                    return Json(
                        new
                            {
                                Result = true,
                                ResultMessage = "Başlık silindi!"
                            },
                        JsonRequestBehavior.AllowGet);
                }

                return
                    Json(
                        new
                            {
                                Result = false,
                                ResultMessage = "Başlık bulunamadı!"
                            },
                        JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(
                    new
                        {
                            Result = false,
                            ResultMessage = "Başlık silinirken hata oluştu!"
                        },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult KeywordTagSelection(int keywordId = 0)
        {
            try
            {
                var keywordTagSelectionListViewModel = new KeywordTagSelectionViewModel
                {
                    KeywordId = keywordId,
                    Tags = _context.Tags.Where(p=>p.TagParentId != null).ToList(),
                    SelectedTags = _context.KeywordTags.Where(p => p.KeywordId == keywordId).Select(p => p.TagId).ToArray()
                };

                return View(keywordTagSelectionListViewModel);
            }
            catch(Exception exception)
            {
                throw new Exception("Error in ManagementController.CreateKeywordTagSelection [Get]", exception);
            }
        }

        [HttpPost]
        public ActionResult KeywordTagSelection(FormCollection form, KeywordTagSelectionViewModel viewModel)
        {
            //...
            // Restore tag list

EStudyBase/Views/Management/CreateContent.cshtml
@model EStudyBase.ViewModels.CreateContentViewModel
@{
    ViewBag.Title = "İçerik Ekle";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_BackEndLayout.cshtml";
    }
}

<div id="divCreateContent">
    <table class="table table-striped table-bordered table-condensed table-hover table-centered">
        <tr>
            <td>
                @using (Ajax.BeginForm("CreateContent", "Content",
                                       new AjaxOptions
                                           {
                                               InsertionMode = InsertionMode.Replace,
                                               UpdateTargetId = "divCreateContent",
                                               OnSuccess = "RestoreOperationsContent"
                                           }, new { id = "ContentForm", enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.KeywordId)
                    <div id="Result">
                        @if (ViewBag.Result != null)
                        {
                            if (!ViewBag.Result)
                            {
                                if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                                {
                                    <div class="alert alert-error">@ViewBag.ResultMessage</div>
                                }
                            }
                            else
                            {
                                if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                                {
                                    <div class="alert alert-success">@ViewBag.ResultMessage</div>
                                }
                            }
                        }
                    </div>
                
                    <div class="control-group">
                        @Html.LabelFor(model => model.LanguageId, new { @class = "control-label" })
                        <div class="controls">
                            @Html.DropDownListFor(model => model.LanguageId, new SelectList(Model.Languages, "Value", "Text"))
                        </div>
                        @Html.ValidationMessageFor(model => model.LanguageId)
                    </div>
                
                    <div class="control-group">
                        @Html.LabelFor(model => model.ContentCategoryId, new { @class = "control-label" })
                        <div class="controls">
                            @Html.DropDownListFor(model => model.ContentCategoryId, new SelectList(Model.ContentCategories, "Value", "Text"))
                        </div>
                        @Html.ValidationMessageFor(model => model.ContentCategoryId)
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Description, new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextAreaFor(model => model.Description, new { id = "txtDescription" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <div id="upload">
                                <div id="drop">
                                    Dosyalarınızı buraya sürükleyin
                                    <a>Yükle</a>
                                    <input type="file" name="PostedFile" />
                                </div>

                                <ul>
                                    <!-- The file uploads will be shown here -->
                                </ul>
                            </div>
                        </div>
                    </div>
                
                    <div class="control-group">
                        <div class="controls">
                            <input id="BtnCreateContent" type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                }
            </td>
        </tr>
    </table>
</div>

EStudyBase/Views/Management/CreateKeyword.cshtml
@using EStudyBase.Extensions
@model EStudyBase.ViewModels.KeywordViewModel
@{
    ViewBag.Title = "Başlık Ekle";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_BackEndLayout.cshtml";
    }
}

<div id="divCreateKeyword">
    <table class="table table-striped table-bordered table-condensed table-hover table-centered">
        <tr>
            <td>
                @using (Ajax.BeginForm("CreateKeyword", "Management",
                                           new AjaxOptions
                                               {
                                                   UpdateTargetId = "divCreateKeyword",
                                                   InsertionMode = InsertionMode.Replace,
                                                   OnComplete = "RestoreOperationsContent"
                                               }, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.ValidationSummary(true)
                    if (ViewBag.Result != null)
                    {
                        if (!ViewBag.Result)
                        {
                            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                            {
                    <div class="alert alert-error">@ViewBag.ResultMessage</div>
                            }
                        }
                        else
                        {
                            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                            {
                    <div class="alert alert-success">@ViewBag.ResultMessage</div>
                            }
                        }
                    }
                    
                    <div class="control-group">
                        @Html.LabelFor(model => model.Definition, new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Definition)
                        </div>
                        @Html.ValidationMessageFor(model => model.Definition)
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Synonym, new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Synonym)
                        </div>
                        @Html.ValidationMessageFor(model => model.Synonym)
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Antonym, new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Antonym)
                        </div>
                        @Html.ValidationMessageFor(model => model.Antonym)
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Order, new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Order)
                        </div>
                        @Html.ValidationMessageFor(model => model.Order)
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.LanguageId, new { @class = "control-label" })
                        <div class="controls">
                            @Html.DropDownListFor(model => model.LanguageId, new SelectList(Model.Languages, "Value", "Text"))
                        </div>
                        @Html.ValidationMessageFor(model => model.LanguageId)
                    </div>
                     
                    <div class="control-group">
                        @Html.LabelFor(model => model.Tags, new { @class = "control-label" })
                        <div class="controls">
                            <div class="checkbox-container">
                                @Html.CheckBoxListFor("SelectedTags", Model.Tags, "Definition", "TagId", Model.SelectedTags)
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.SelectedTags)
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Approved, new { @class = "control-label" })
                        <div class="controls">
                            @Html.CheckBoxFor(model => model.Approved)
                        </div>
                        @Html.ValidationMessageFor(model => model.Approved)
                    </div>

                    <div class="control-group">
                        <div class="controls">
                            <input type="submit" value="Oluştur" class="btn btn-primary" />
                        </div>
                    </div>
                }
            </td>
        </tr>
    </table>
</div>

EStudyBase/Views/Management/KeywordContentList.cshtml
@{
    ViewBag.Title = "İçerik Listesi";
    Layout = "~/Views/Shared/_BackEndLayout.cshtml";
}

<div class="container" style="margin-top: 10px">
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered jquery-data-table" >
        <thead>
            <tr>
                <th>Dil</th>
                <th>Açıklama</th>
                <th>Kullanıcı</th>
                <th># Şikayet</th>
                <th>Tarih</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
</div>

EStudyBase/Views/Management/KeywordList.cshtml
@{
    ViewBag.Title = "Başlık Listesi";
    Layout = "~/Views/Shared/_BackEndLayout.cshtml";
}

<div id="divOperations">
</div>
<table class="table table-striped table-bordered table-condensed table-hover table-centered">
    <tr>
        <td>
            @Html.ActionLink("Yeni Başlık", "CreateKeyword", "Management", null, new { target = "_blank",@class="btn btn-primary" })
        </td>
    </tr>
</table>
<div class="container" style="margin-top: 10px">
    <table class="table table-striped table-bordered jquery-data-table" >
        <thead>
            <tr role="row">
                <th>Id</th>
                <th>Başlık</th>
                <th>Dil</th>
                <th>Kullanıcı</th>
                <th>Tarih</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
</div>

EStudyBase/Views/Management/KeywordTagSelection.cshtml
@using EStudyBase.Extensions
@model EStudyBase.ViewModels.KeywordTagSelectionViewModel

@{
    ViewBag.Title = "Başlık-Tag Seçimi";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_BackEndLayout.cshtml";
    }
}

<div id="divKeywordTagSelection">
    <table class="table table-striped table-bordered table-condensed table-hover table-centered">
        <tr>
            <td>
                @using (Ajax.BeginForm("KeywordTagSelection", "Management",
                                   new AjaxOptions
                                       {
                                           UpdateTargetId = "divKeywordTagSelection",
                                           InsertionMode = InsertionMode.Replace,
                                           OnComplete = "RestoreOperationsContent"
                                       }, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.ValidationSummary(true)
                    if (ViewBag.Result != null)
                    {
                        if (!ViewBag.Result)
                        {
                            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                            {
                    <div class="alert alert-error">@ViewBag.ResultMessage</div>
                            }
                        }
                        else
                        {
                            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                            {
                    <div class="alert alert-success">@ViewBag.ResultMessage</div>
                            }
                        }
                    }
                
                    @Html.HiddenFor(model => model.KeywordId)

                    <div class="control-group">
                        @Html.LabelFor(model => model.Tags, new { @class = "control-label" })
                        <div class="controls">
                            <div class="checkbox-container">
                                @Html.CheckBoxListFor("SelectedTags", Model.Tags, "Definition", "TagId", Model.SelectedTags)
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.SelectedTags)
                    </div>
                    
                    <div class="control-group">
                        <div class="controls">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                }
            </td>
        </tr>
    </table>
</div>

EStudyBase/Views/Management/UserList.cshtml
@{
    ViewBag.Title = "Kullanıcı Listesi";
    Layout = "~/Views/Shared/_BackEndLayout.cshtml";
}


<div class="container" style="margin-top: 10px">
    <table class="table table-striped table-bordered jquery-data-table" >
        <thead>
            <tr role="row">
                <th>User Id</th>
                <th>User Name</th>
                <th>Email</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
</div>

EStudyBase/Views/Management/_UserRoleSelection.cshtml
@using EStudyBase.Extensions
@model EStudyBase.ViewModels.UserRoleSelectionViewModel


<!-- Modal -->
<div class="modal hide fade" id="modalUserRoleSelection" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/custom")

    <script type="text/javascript" src="/Scripts/Custom/mvc-bootstrap-integration.js"></script>
    <script type="text/javascript" src="/Scripts/Custom/modal.js"></script>

    <script type="text/javascript">
        function RebuildModal(response) {
            $('.modal-backdrop').each(function () {
                $(this).remove();
            });

            $('#modalUserRoleSelection').replaceWith(response);
            $('#modalUserRoleSelection').modal();
        }
    </script>

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button id="closeModal" type="button" class="close close-modal" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">@Model.UserName kullanıcısı için rol tanımla</h4>
            </div>
            <div style="height: 10px;"></div>
            @using (Ajax.BeginForm("UserRoleSelection", "Management",
                                   new AjaxOptions
                                       {
                                           OnSuccess = "RebuildModal"
                                       }, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
            {
                @Html.ValidationSummary(true)
                if (ViewBag.Result != null)
                {
                    if (!ViewBag.Result)
                    {
                        if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                        {
                <div class="alert alert-error">@ViewBag.ResultMessage</div>
                        }
                    }
                    else
                    {
                        if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                        {
                <div class="alert alert-success">@ViewBag.ResultMessage</div>
                        }
                    }
                }
                
                @Html.HiddenFor(model => model.UserId)

                <div class="control-group">
                    @Html.LabelFor(model => model.UserRole, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.UserRole, new SelectList(ViewBag.Roles, "Value", "Text"))
                    </div>
                    @Html.ValidationMessageFor(model => model.UserRole)
                </div>
                    
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>