EStudyBase/Models/Content.cs
using System;

namespace EStudyBase.Models {
    public class Content {
        public int ContentId { get; set; }
        public int KeywordId { get; set; }
        public int LanguageId { get; set; }
        public string Url { get; set; }
        public decimal? FileSize { get; set; }
        public string Description { get; set; }
        public ContentType ContentType { get; set; }
        public int ContentCategoryId { get; set; }
        public int CreateUserId { get; set; }
        public int? ModifyUserId { get; set; }
        public bool Approved { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
        public int Complaint { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public virtual ContentCategory ContentCategory { get; set; }
        public virtual Keyword Keyword { get; set; }
        public virtual Language Language { get; set; }
        public virtual UserProfile CreateUser { get; set; }
        public virtual UserProfile ModifyUser { get; set; }
    }
}

EStudyBase/Models/ContentType.cs
namespace EStudyBase.Models
{
    public enum ContentType
    {
        Translation = 1,
        FileUpload = 2,
        VoiceRecord = 3
    }
}

EStudyBase/ViewModels/ContentViewModel.cs
using System;
using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class ContentViewModel
    {
        public int KeywordId { get; set; }
        public string LanguageDefinition { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string UserName { get; set; }
        public int ContentId { get; set; }
        public bool Approved { get; set; }
        public int Complaint { get; set; }
        public DateTime CreateDate { get; set; }
        public ContentType ContentType { get; set; }
    }
}

EStudyBase/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EStudyBase.Attributes;
using EStudyBase.Filters;
using EStudyBase.Models;
using EStudyBase.ViewModels;
using WebMatrix.WebData;

namespace EStudyBase.Controllers {
    [InitializeSimpleMembership]
    public class ContentController : Controller {
        private readonly EStudyBaseContext _context = new EStudyBaseContext();
        private const string UploadFilePath = "/UploadFiles";
        private readonly List<string> _allowedFileExtensions = new List<string>
            {
                ".JPG",
                ".JPE",
                ".BMP",
                ".GIF",
                ".PNG",
                ".AVI",
                ".MP4",
                ".FLV",
                ".MOV",
                ".M4V",
                ".F4V"
            };

        [AjaxAuthorize]
        public ActionResult CreateKeyword() {
            try {
                var viewModel = new KeywordViewModel {
                    Languages = _context
                        .Languages
                        .Select(language => new SelectListItem {
                            Text = language.Definition,
                            Value = SqlFunctions.StringConvert((double?)language.LanguageId).Trim()
                        })
                        .ToList(),
                    Tags = _context.Tags.Where(p => p.TagParentId != null).ToList()
                };

                return PartialView("_NewKeyword", viewModel);
            }
            catch (Exception exception) {
                throw new Exception("Error in ManagementController.CreateKeyword [Get]", exception);
            }
        }

        [AjaxAuthorize]
        [HttpPost]
        public ActionResult CreateKeyword(FormCollection form, KeywordViewModel viewModel) {
            try {
                //...
                // Languages
                viewModel.Languages = _context
                    .Languages
                    .Select(language => new SelectListItem {
                        Text = language.Definition,
                        Value = SqlFunctions.StringConvert((double?)language.LanguageId).Trim()
                    })
                    .ToList();

                //...
                // Tags
                viewModel.Tags = _context.Tags.Where(p => p.TagParentId != null).ToList();

                // ...
                // Validations
                if (string.IsNullOrWhiteSpace(viewModel.Definition)) {
                    ViewBag.Result = false;
                    ViewBag.ResultMessage = "Lütfen başlık bölümünü doldurunuz!";
                    return PartialView("_NewKeyword", viewModel);
                }

                if (viewModel.SelectedTags == null) {
                    ViewBag.Result = false;
                    ViewBag.ResultMessage = "Lütfen en az bir etiket seçiniz!";
                    return PartialView("_NewKeyword", viewModel);
                }

                // Check keyword for existence
                var keywordExists = _context.Keywords.Any(p => p.Definition.ToLower().Equals(viewModel.Definition.ToLower()));

                if (keywordExists) {
                    ViewBag.Result = false;
                    ViewBag.ResultMessage = "Bu başlık daha önceden girilmiş.";
                    return PartialView("_NewKeyword", viewModel);
                }

                //...
                // Create Keyword
                var keyword = new Keyword {
                    Definition = viewModel.Definition,
                    LanguageId = viewModel.LanguageId,
                    Synonym = viewModel.Synonym,
                    Antonym = viewModel.Antonym,
                    //Order = viewModel.Order,
                    Approved = true,
                    CreateUserId = WebSecurity.CurrentUserId,
                    CreateDate = DateTime.Now
                };

                _context.Keywords.Add(keyword);
                _context.SaveChanges();

                //...
                // Create Tags for newly created keyword
                foreach (var item in form["SelectedTags"].Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries)) {
                    var keywordTag = new KeywordTag {
                        KeywordId = keyword.KeywordId,
                        TagId = Convert.ToInt32(item),
                        CreateDate = DateTime.Now
                    };
                    _context.KeywordTags.Add(keywordTag);
                }

                //...
                // Save changes
                _context.SaveChanges();

                ViewBag.Result = true;
                ViewBag.ResultMessage = "Girdiğiniz içerik başarıyla kaydedilmiştir.";
                return PartialView("_NewKeyword", viewModel);
            }
            catch (Exception exception) {
                throw new Exception("Error in ContentController.CreateKeyword [Post]", exception);
            }

        }

        public JsonResult GetContentDetailsByContentId(int contentId = 0) {
            var content =
                _context.Contents
                    .Include(p => p.Keyword)
                    .FirstOrDefault(p => p.ContentId == contentId);
            if (content != null) {
                return
                    Json(
                        new {
                            keywordId = content.Keyword.KeywordId,
                            ShareUrl = string.Format("http://estudybase.com/?Term={0}&ContentId={1}", content.Keyword.Definition, contentId),
                            ShareDescription = string.Format("{0} {1}", content.Keyword.Definition, content.Description),
                            Result = true
                        },
                        JsonRequestBehavior.AllowGet);
            }

            return
                Json(
                    new {
                        Result = false,
                        ResultMessage = "İçerik bilgisi bulunamadı, lütfen daha sonra tekrar deneyiniz!"
                    },
                    JsonRequestBehavior.AllowGet);
        }

        [AjaxAuthorize]
        public PartialViewResult CreateContent(int keywordId = 0) {
            var viewModel = new CreateContentViewModel {
                KeywordId = keywordId,
                Languages = _context
                    .Languages
                    .Select(language => new SelectListItem {
                        Text = language.Definition,
                        Value = SqlFunctions.StringConvert((double?)language.LanguageId).Trim()
                    })
                    .ToList(),
                ContentCategories = _context
                    .ContentCategories
                    .Select(category => new SelectListItem {
                        Text = category.Definition,
                        Value = SqlFunctions.StringConvert((double?)category.ContentCategoryId).Trim()
                    })
                    .ToList()
            };

            return PartialView("_NewContent", viewModel);
        }

        [AjaxAuthorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateContent(CreateContentViewModel viewModel) {
            viewModel.Languages = _context
                .Languages
                .Select(language => new SelectListItem {
                    Text = language.Definition,
                    Value = SqlFunctions.StringConvert((double?)language.LanguageId).Trim()
                })
                .ToList();
            viewModel.ContentCategories = _context
                .ContentCategories
                .Select(category => new SelectListItem {
                    Text = category.Definition,
                    Value = SqlFunctions.StringConvert((double?)category.ContentCategoryId).Trim()
                })
                .ToList();

            if (string.IsNullOrWhiteSpace(viewModel.Description)) {
                ViewBag.Result = false;
                ViewBag.ResultMessage = "Lütfen açıklama giriniz!";
                return PartialView("_NewContent", viewModel);
            }

            var fileName = string.Empty;
            if (viewModel.PostedFile != null) {
                //... 
                // Check File Size
                if (viewModel.PostedFile.ContentLength > 10 * 1024 * 1024) {
                    ViewBag.Result = false;
                    ViewBag.ResultMessage = "Dosya boyutu max 10 MB olabilir!";
                    return PartialView("_NewContent", viewModel);
                }

                //...
                // Check file extensions
                if (!_allowedFileExtensions.Contains(new FileInfo(viewModel.PostedFile.FileName).Extension.ToUpper())) {
                    ViewBag.Result = false;
                    ViewBag.ResultMessage = "Bu dosya formatı desteklenmiyor, lütfen resim veya video dosyası ekleyiniz!";
                    return PartialView("_NewContent", viewModel);
                }

                //...
                // Get Keyword Definition
                var keyword = _context.Keywords.FirstOrDefault(p => p.KeywordId == viewModel.KeywordId);
                if (keyword != null) {
                    fileName = SaveUploadedFile(HttpContext.ApplicationInstance.Context, keyword.KeywordId, keyword.Definition);
                    if (string.IsNullOrWhiteSpace(fileName)) {
                        ViewBag.Result = false;
                        ViewBag.ResultMessage = "Dosya yüklenirken hata oluştu, lütfen daha sonra tekrar deneyiniz!";
                        return PartialView("_NewContent", viewModel);
                    }
                }
                else {
                    ViewBag.Result = false;
                    ViewBag.ResultMessage = "başlık bilgisi bulunamadı, lütfen daha sonra tekrar deneyiniz!";

EStudyBase/Views/Content/_NewContent.cshtml
@model EStudyBase.ViewModels.CreateContentViewModel
<h3 class="icerikbasliklari">yeni tanım ekle</h3>
            @using (Ajax.BeginForm("CreateContent", "Content",
                                   new AjaxOptions
                                       {
                                           InsertionMode = InsertionMode.Replace,
                                           UpdateTargetId = "divOperations",
                                           OnSuccess = "RestoreOperationsContent"
                                       }, new { id = "ContentForm", enctype = "multipart/form-data", @class = "form-horizontal" }))
            {
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.KeywordId)
                <div id="Result">
                    @if (ViewBag.Result != null)
                    {
                        if (!ViewBag.Result)
                        {
                            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                            {
                        <div class="alert alert-error">@ViewBag.ResultMessage</div>
                            }
                        }
                        else
                        {
                            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
                            {
                        <div class="alert alert-success">@ViewBag.ResultMessage</div>
                            }
                        }
                    }
                </div>
                
                <div class="control-group">
                    @Html.LabelFor(model => model.LanguageId, new { @class = "control-label" })
                    <div class="controls" style="margin-left:85px;">
                        @Html.DropDownListFor(model => model.LanguageId, new SelectList(Model.Languages, "Value", "Text"))
                    </div>
                    @Html.ValidationMessageFor(model => model.LanguageId)
                </div>
                
                <div class="control-group">
                    @Html.LabelFor(model => model.ContentCategoryId, new { @class = "control-label" })
                    <div class="controls" style="margin-left:85px;">
                        @Html.DropDownListFor(model => model.ContentCategoryId, new SelectList(Model.ContentCategories, "Value", "Text"))
                    </div>
                    @Html.ValidationMessageFor(model => model.ContentCategoryId)
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label" })
                    <div class="controls" style="margin-left:85px;">
                        @Html.TextAreaFor(model => model.Description, new { id = "txtDescription" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Description)
                </div>          
                <div class="control-group saga" style="margin-right:22px;">
                    <div class="controls">
                        <div id="upload" class="sola">
                            <div id="drop" style="padding:0;border:none;border-radius:0;text-align:left;display:inline-block;">
                                <a class="gri-buton" style="margin-right:20px;">dosya ekle *</a>
                                <input type="file" name="PostedFile" />
                            </div>
                            @*<ul>
                                <!-- The file uploads will be shown here -->
                            </ul>*@
                        </div>
                        <input id="BtnCreateContent" type="submit" value="kaydet" class="yesil-buton"/>
                    </div>
                </div>
                <div class="control-group saga" style="margin-right:22px;">
                    <div class="controls">
                        <div class="progress progress-striped active"><div id="FileUploadProgress" class="bar"></div><span id="Percentage">%0</span></div>
                        <div class="alert alert-error" style="font-style: italic;font-size: 11px;width: 485px;height: 20px;">* Desteklenen dosya formatları: jpg,jpe,bmp,gif,png,avi,mp4,flv,mov,m4v,f4v</div> 
                    </div>
                </div>
            }

EStudyBase/Views/Content/_NewKeyword.cshtml
@using EStudyBase.Extensions
@model EStudyBase.ViewModels.KeywordViewModel
@{
    ViewBag.Title = "Create Keyword";
}


<h3 class="icerikbasliklari">yeni başlık ekle</h3>
@using (Ajax.BeginForm("CreateKeyword", "Keyword",
                                           new AjaxOptions
                                               {
                                                   InsertionMode = InsertionMode.Replace,
                                                   UpdateTargetId = "divOperations",
                                                   OnSuccess = "RestoreOperationsContent"
                                               }, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    if (ViewBag.Result != null)
    {
        if (!ViewBag.Result)
        {
            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
            {
    <div class="alert alert-error">@ViewBag.ResultMessage</div>
            }
        }
        else
        {
            if (!string.IsNullOrWhiteSpace(ViewBag.ResultMessage))
            {
    <div class="alert alert-success">@ViewBag.ResultMessage</div>
            }
        }
    }

    <div class="control-group">
        @Html.LabelFor(model => model.Definition, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(model => model.Definition)
        </div>
        @Html.ValidationMessageFor(model => model.Definition)
    </div>
                    
    <div class="control-group">
        @Html.LabelFor(model => model.Synonym, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(model => model.Synonym)
        </div>
        @Html.ValidationMessageFor(model => model.Synonym)
    </div>

    <div class="control-group">
        @Html.LabelFor(model => model.Antonym, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(model => model.Antonym)
        </div>
        @Html.ValidationMessageFor(model => model.Antonym)
    </div>

    <div class="control-group">
        @Html.LabelFor(model => model.LanguageId, new { @class = "control-label" })
        <div class="controls">
            @Html.DropDownListFor(model => model.LanguageId, new SelectList(Model.Languages, "Value", "Text"))
        </div>
        @Html.ValidationMessageFor(model => model.LanguageId)
    </div>
                     
    <div class="control-group">
        @Html.LabelFor(model => model.Tags, new { @class = "control-label" })
        <div class="controls">
            <div class="checkbox-container" style="width: 440px;">
                @Html.CheckBoxListFor("SelectedTags", Model.Tags, "Definition", "TagId", Model.SelectedTags)
            </div>
        </div>
        @Html.ValidationMessageFor(model => model.SelectedTags)
    </div>

    <div class="control-group saga" style="margin-right:22px;">
        <div class="controls">
            <input type="submit" value="kaydet" class="yesil-buton"/>
        </div>
    </div>
}

EStudyBase/Views/Content/_NewRecord.cshtml
@model EStudyBase.ViewModels.CreateContentViewModel
<h3 class="icerikbasliklari">yeni ses kaydı ekle</h3>
@using (Ajax.BeginForm("CreateRecord", "Content",
        new AjaxOptions
            {
            }, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    <div id="divRecordResult_@Model.KeywordId" style="display: none;"></div>
    <div class="control-group">
        <div class="controls" style="margin-left:0;">
            <span style="padding-right:45px;font-size:14px;">Araçlar</span>
            <a href="javascript:record($('#record_@Model.KeywordId'))" id="record_@Model.KeywordId" class="icon-play-circle" data-toggle="tooltip" title="Kaydetmeye başla" data-keywordid="@Model.KeywordId"></a>
            <a href="javascript:play($('#play_@Model.KeywordId'))" id="play_@Model.KeywordId" class="icon-play" data-toggle="tooltip" title="Oynat" data-keywordid="@Model.KeywordId"></a>
            <a href="javascript:stop($('#stop_@Model.KeywordId'))" id="stop_@Model.KeywordId" class="icon-stop" data-toggle="tooltip" title="Durdur" data-keywordid="@Model.KeywordId"></a>
            @*
            <a href="javascript:upload($('#upload_@Model.KeywordId'))" id="upload_@Model.KeywordId" class="icon-upload" data-toggle="tooltip" title="Yükle" data-keywordid="@Model.KeywordId"></a>
            *@
            <a href="#" id="time_@Model.KeywordId">0:00</a>
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.LanguageId, new { @class = "control-label" })
        <div class="controls" style="margin-left: 85px;">
            @Html.DropDownListFor(model => model.LanguageId, new SelectList(Model.Languages, "Value", "Text"))
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.ContentCategoryId, new { @class = "control-label" })
        <div class="controls" style="margin-left: 85px;">
            @Html.DropDownListFor(model => model.ContentCategoryId, new SelectList(Model.ContentCategories, "Value", "Text"))
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label" })
        <div class="controls" style="margin-left: 85px;">
            <textarea id="txtRecordDescription" name="txtRecordDescription"></textarea>
        </div>
    </div>
    <div class="control-group">
        <div class="controls saga" style="margin-left:0;margin-right:21px;">
            <a href="javascript:upload($('#upload_@Model.KeywordId'))" id="upload_@Model.KeywordId" class="yesil-buton" data-toggle="tooltip" title="Upload" data-keywordid="@Model.KeywordId">kaydet</a>
        </div>
    </div>
}