EStudyBase/Controllers/EmailController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using EStudyBase.Attributes;
using EStudyBase.Filters;
using EStudyBase.Mailers;
using EStudyBase.Models;
using EStudyBase.ViewModels;
using Mvc.Mailer;
using WebMatrix.WebData;

namespace EStudyBase.Controllers
{
    [InitializeSimpleMembership]
    [AjaxAuthorize]
    public class EmailController : Controller
    {
        private readonly EStudyBaseContext _context = new EStudyBaseContext();

        private IUserMailer _userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return _userMailer; }
            set { _userMailer = value; }
        }

        public ActionResult EmailBox(string userName = "", int emailId = 0)
        {
            var loggedInUserId = WebSecurity.CurrentUserId;
            var allCount = _context.EmailLogs.Count(p => p.FromUserId == loggedInUserId || p.ToUserId == loggedInUserId);
            var inboxCount = _context.EmailLogs.Count(p => p.ToUserId == loggedInUserId);
            var outboxCount = _context.EmailLogs.Count(p => p.FromUserId == loggedInUserId);
            var unReadCount = _context.EmailLogs.Count(p => p.ToUserId == loggedInUserId && !p.Read);
            var deletedCount =
                _context.EmailLogs.Count(
                    p => (p.FromUserId == loggedInUserId || p.ToUserId == loggedInUserId) && p.Deleted);

            ViewBag.AllCount = allCount;
            ViewBag.InboxCount = inboxCount;
            ViewBag.OutboxCount = outboxCount;
            ViewBag.UnReadCount = unReadCount;
            ViewBag.DeletedCount = deletedCount;
            ViewBag.ToUserId = WebSecurity.GetUserId(userName);
            ViewBag.EmailId = emailId;

            return View();
        }

        public ActionResult GetEmailBox(string operationType, int currentPage = 1, string pageDirection = null)
        {
            if (pageDirection != null && pageDirection.Equals("Next"))
            {
                currentPage++;
            }
            if (pageDirection != null && pageDirection.Equals("Previous"))
            {
                currentPage--;
            }
            ViewBag.CurrentPage = currentPage;
            ViewBag.OperationType = operationType;
            var skip = (currentPage - 1) * 10;

            int loggedInUserId = WebSecurity.CurrentUserId;
            var query = _context.EmailLogs
                                       .Include(p => p.FromUser)
                                       .Include(p => p.ToUser)
                                       .Include(p => p.EmailLogType);
            switch (operationType)
            {
                case "All":
                    query = query.Where(p => p.ToUserId == loggedInUserId || p.FromUserId == loggedInUserId);
                    ViewBag.ListHeader = "Tüm Mesajlar";
                    ViewBag.ListCount = query.Count();
                    break;
                case "Inbox":
                    query = query.Where(p => p.ToUserId == loggedInUserId);
                    ViewBag.ListHeader = "Gelen Mesajlar";
                    ViewBag.ListCount = query.Count();
                    break;
                case "Outbox":
                    query = query.Where(p => p.FromUserId == loggedInUserId);
                    ViewBag.ListHeader = "Giden Mesajlar";
                    ViewBag.ListCount = query.Count();
                    break;
                case "UnRead":
                    query = query.Where(p => p.ToUserId == loggedInUserId && !p.Read);
                    ViewBag.ListHeader = "Okunmamış Mesajlar";
                    ViewBag.ListCount = query.Count();
                    break;
                case "Deleted":
                    query =
                        query.Where(p => (p.ToUserId == loggedInUserId || p.FromUserId == loggedInUserId) && p.Deleted);
                    ViewBag.ListHeader = "Silinen Mesajlar";
                    ViewBag.ListCount = query.Count();
                    break;
                default:
                    query = query.Where(p => p.ToUserId == loggedInUserId || p.FromUserId == loggedInUserId);
                    ViewBag.ListHeader = "Tüm Mesajlar";
                    ViewBag.ListCount = query.Count();
                    break;
            }

            var emailBoxList =
                query
                    .OrderByDescending(p => p.CreateDate)
                    .Skip(skip)
                    .Take(10)
                    .Select(p => new EmailBoxViewModel
                    {
                        EmailId = p.EmailId,
                        FromUserId = p.FromUserId,
                        FromUserName = p.FromUser.UserName,
                        FromUserEmail = p.FromUser.Email,
                        ToUserId = p.ToUser.UserId,
                        ToUserName = p.ToUser.UserName,
                        ToUserEmail = p.ToUser.Email,
                        Header = p.Header,
                        Content = p.Content,
                        EmailTypeId = p.EmailTypeId,
                        EmailType = p.EmailLogType.Description,
                        CreateDate = p.CreateDate
                    }).ToList();

            return PartialView("_EmailBoxList", emailBoxList);
        }

        public ActionResult GetUnreadEmailCount()
        {
            int loggedInUserId = WebSecurity.CurrentUserId;
            var unreadEmailCount = _context.EmailLogs.Count(p => p.ToUserId == loggedInUserId && !p.Read);

            return Content(string.Format(@"<a href='/Email/EmailBox' target='_blank'>
                                                    mesajlar <span class='badge'>{0}</span>
                                                </a>", unreadEmailCount));
        }

        public ActionResult GetEmailContent(int emailId)
        {
            int loggedInUserId = WebSecurity.CurrentUserId;
            var emailBoxViewModel = _context.EmailLogs
                                            .Include(p => p.FromUser)
                                            .Include(p => p.ToUser)
                                            .Include(p => p.EmailLogType)
                                            .Where(
                                                p =>
                                                p.EmailId == emailId &&
                                                (p.FromUserId == loggedInUserId || p.ToUserId == loggedInUserId))
                                            .Select(p => new EmailBoxViewModel
                                            {
                                                EmailId = p.EmailId,
                                                FromUserId = p.FromUserId,
                                                FromUserName = p.FromUser.UserName,
                                                FromUserEmail = p.FromUser.Email,
                                                ToUserId = p.ToUser.UserId,
                                                ToUserName = p.ToUser.UserName,
                                                ToUserEmail = p.ToUser.Email,
                                                Header = p.Header,
                                                Content = p.Content,
                                                EmailTypeId = p.EmailTypeId,
                                                EmailType = p.EmailLogType.Description,
                                                CreateDate = p.CreateDate
                                            }).FirstOrDefault();

            //...
            // Mark email as read
            if (emailBoxViewModel != null)
            {
                var emailLog = _context.EmailLogs.FirstOrDefault(p => p.EmailId == emailBoxViewModel.EmailId);
                if (emailLog != null)
                {
                    emailLog.Read = true;
                    _context.SaveChanges();
                }
            }

            return PartialView("_EmailContent", emailBoxViewModel);
        }

        public ActionResult DeleteEmail(int emailid)
        {
            var emailLog = _context.EmailLogs.FirstOrDefault(p => p.EmailId == emailid);
            if (emailLog != null)
            {
                emailLog.Deleted = true;
                _context.SaveChanges();
            }

            return JavaScript("bootbox.alert('Mesajınız başarıyla silinmiştir!')");
        }

        public ActionResult EmailToUser(int userId = 0)
        {
            try
            {
                var user = _context.UserProfiles.FirstOrDefault(p => p.UserId == userId);
                if (user != null)
                {
                    var viewModel = new EmailViewModel
                    {
                        ToUserId = userId,
                        UserName = user.UserName
                    };
                    return PartialView("_EmailToUser", viewModel);
                }
                return PartialView("_EmailToUser");
            }
            catch (Exception exception)
            {
                throw new Exception("Error in EmailController.EmailToUser [Get]", exception);
            }
        }

        [HttpPost]
        public ActionResult EmailToUser(EmailViewModel viewModel)
        {
            // Check model state
            if (!ModelState.IsValid)
            {
                ViewBag.Result = false;
                ViewBag.ResultMessage = "Lütfen belirtilen alanları doldurunuz!";

                return PartialView("_EmailToUser", viewModel);
            }

            try
            {
                var fromUserName = WebSecurity.CurrentUserName;
                var toUser = _context.UserProfiles.FirstOrDefault(p => p.UserId == viewModel.ToUserId);

                const string view = "EmailTemplate";
                var header = string.Format("{0}", viewModel.Subject);
                var content = viewModel.Body;

                //...

EStudyBase/Views/Shared/_BackEndLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/datatables/css")
    <link rel="stylesheet" type="text/css" href="/Content/sitestyle/style.css" />

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/datatables")
    <script type="text/javascript" src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    <!-- Html Editor -->
    <link href="/Content/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" />
    <script src="/Content/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
    <script src="/Content/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
    
    <!-- jQuery File Upload Dependencies -->
    <link rel="stylesheet" type="text/css" href="/Content/fileupload/assets/css/style.css" />
    <script src="/Content/fileupload/assets/js/jquery.knob.js"></script>
    <script src="/Content/fileupload/assets/js/jquery.ui.widget.js"></script>
    <script src="/Content/fileupload/assets/js/jquery.iframe-transport.js"></script>
    <script src="/Content/fileupload/assets/js/jquery.fileupload.js"></script>
    <script src="/Content/fileupload/assets/js/script.js"></script>

    @Scripts.Render("~/bundles/custom/js")
    <script type="text/javascript" src="/Scripts/CustomBackend/management.js"></script>
    <style type="text/css">
        .checkbox-container
        {
            background-color: #ffffff;
            border: 1px solid #cccccc;
            width: 700px;
            height: 100px;
            border-radius: 4px;
            overflow-y: scroll;
        }
    </style>
    <style type="text/css">
        textarea {
           width: 700px;
           height: 100px;
        }
    </style>
</head>
<body>
    <div class="container">
        <ul class="nav nav-pills">
            <li class="active"><a href="/Keyword/Search">Siteye Dön</a></li>
            <li><a href="/Management/KeywordList">Başlıklar</a></li>
            @if(Roles.IsUserInRole(WebSecurity.CurrentUserName,"Admin"))
            {
                <li><a href="/Management/UserList">Kullanıcılar</a></li>
            }
            @Html.Partial("_LoginPartial")
        </ul>
        @RenderSection("featured", required: false)
        <section>
            @RenderBody()
        </section>
        
        <div id="Loading" style="display: none;">
            <img alt="Yükleniyor..." src="/Images/icons/ajax-loader.gif">
        </div>

        @RenderSection("scripts", required: false)
    </div>
    
    <script type="text/javascript">
        function RestoreOperationsContent() {
            $('textarea').wysihtml5();
            $('html,body').animate({ scrollTop: $('body').offset().top }, 'slow');
        }
    </script>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').wysihtml5();
        });
    </script>
    <script type="text/javascript">
        $(document)
            .bind("ajaxSend", function () {
                $("#Loading").show();
            })
            .bind("ajaxComplete", function () {
                $("#Loading").hide();
            })
            .bind('ajaxError', function () {
                $("#Loading").hide();
            });
    </script>

    <script type="text/javascript">
        $(function () {
            $(document).ajaxError(function (e, xhr) {
                if (xhr.status == 403) {
                    $('#Login').click();
                }
            });
        });
    </script>
    
    <script type="text/javascript">
        $(function () {
            window.onerror = function (message, url, line) {
                bootbox.alert('İşleminiz gerçekleştirilirken hata oluştu, lütfen tekrar deneyiniz!');
                console.log(message);
                return true; //if you return true it overrides default browser error message, at least it should
            };
        });
    </script>
</body>
</html>

EStudyBase/Views/Shared/_FrontEndLayout.cshtml
@using System.Text.RegularExpressions
@using EStudyBase.ViewModels
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>estudybase - Yepyeni Sesli Resimli Videolu İngilizce Sözlük Sitesi,İngilizce Çalışma Ve Bilgi Platformu</title>
    <link href="/Content/custom/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/custom/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="/Content/custom/css/style.css" />
    <link rel="stylesheet" type="text/css" href="/Content/custom/js/scroll/min/perfect-scrollbar-0.4.5.min.css" />
    @Scripts.Render("~/bundles/bootstrap/js")
    <!-- flowplayer !-->
    <script src="~/Content/flowplayer/flowplayer-3.2.12.min.js"></script>
    <!-- flowplayer !-->
</head>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
    <div id="mainContent">
        <div class="header">
            <div class="websitecenter">
                <div id="Loading">
                    <img alt="Yükleniyor..." src="/Images/icons/ajax-loader.gif">
                </div>
                <a class="logo" href="/" title="anasayfa">
                    <img src="/Content/custom/images/logo.png" alt="e study base" />
                </a>
                <div class="saga responsive1" style="width: 700px; margin-top: 3px;">
                    <span class="searchuptext">@{Html.RenderAction("GetTotalKeywordCount", "Keyword");}</span>
                    @using (Html.BeginForm("Search", "Keyword", FormMethod.Get, new { @class = "form-search", style = "margin:0;" }))
                    {
                        <input type="text" name="Term" id="Term" placeholder="aranacak başlığı giriniz" class="input-xxlarge sola arainput" autocomplete="off" value="@ViewBag.Term" />
                        <input type="submit" name="Search" id="Search" value="ara" class="sola yesil-buton" style="margin-left:5px; font-size: 20px;" />
                    }
                    <div class="saga login-text">
                        @Html.Partial("_LoginPartial")
                        @if (WebSecurity.IsAuthenticated)
                        {
                            Html.RenderAction("GetUnreadEmailCount", "Email");
                        }
                        @if (Roles.IsUserInRole(WebSecurity.CurrentUserName, "Admin"))
                        {
                            @Html.ActionLink("admin", "KeywordList", "Management")
                        }
                    </div>
                </div>
                <div class="clear"></div>
                <div class="headermenu">
                    <ul style="margin: 0;">
                        <li>@Ajax.ActionLink("Son Eklenenler", "GetKeywordList", "Keyword", new {
                                    OperationType = "GetRecentlyAddedKeywordList"
                                }, new AjaxOptions
                                    {
                                        HttpMethod = "GET",
                                        UpdateTargetId = "LeftContent",
                                        InsertionMode = InsertionMode.Replace,
                                        OnComplete = "AjaxCompleted('LeftContent')"
                                    }, new {id="RecentlyAddedkeywordList", style = "font-weight:bold;font-size:13px;" })</li>
                        <li>@Ajax.ActionLink("Popüler", "GetKeywordList", "Keyword", new
                                {
                                    OperationType = "GetPopularKeywordList"
                                }, new AjaxOptions
                                    {
                                        HttpMethod = "GET",
                                        UpdateTargetId = "LeftContent",
                                        InsertionMode = InsertionMode.Replace,
                                        OnComplete = "AjaxCompleted('LeftContent')"
                                    }, new { style = "font-weight:bold;font-size:13px;" })</li>
                        @{
                            Html.RenderAction("GetTags", "Keyword");
                        }
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="websitecenter">
            <div id="solblockjs" class="sola solblock">
                <div id="LeftContent">
                    @{
                        Html.RenderAction("GetKeywordList", "Keyword", new { OperationType = "GetPopularKeywordList" });
                    }
                </div>
            </div>
        </div>
        <div class="main">
            <div class="sola mainicaq">
            @RenderBody()
            <div id="divOperations" class="yeniicerikekle"></div>
            </div>
            <div class="sola reklam-alani">
                <img src="/Content/custom/images/reklam-alani.png" alt="" />
                <br /><br />
                <img src="/Content/custom/images/reklam-alani.png" alt="" />
            </div>
            <div class="clear"></div>
            <div class="footer">
                <div class="sola">
                    <a href="javascript:;" title="">Bize Ulaşın</a>
                    <a href="javascript:;" title="">Kullanım ve Telif Hakları</a>
                    <a href="javascript:;" title="">Gizlilik</a>
                </div>
                <div class="saga">
                    Copyright © 2013-Tüm Hakları Saklıdır.
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    </div>

    <script type="text/javascript" src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.validate.unobtrusive.min.js"></script>

     @Scripts.Render("~/bundles/recorder/js")

    <!-- Scroll bar -->
    <script src="~/Content/custom/js/scroll/min/perfect-scrollbar-0.4.5.min.js"></script>
    <script src="~/Content/custom/js/scroll/min/perfect-scrollbar-0.4.5.with-mousewheel.min.js"></script>

    <!-- Html Editor -->
    <link href="/Content/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" />
    <script src="/Content/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
    <script src="/Content/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

    <!-- jQuery File Upload Dependencies -->
    <link rel="stylesheet" type="text/css" href="/Content/fileupload/assets/css/style.css" />
    <script src="/Content/fileupload/assets/js/jquery.knob.js"></script>
    <script src="/Content/fileupload/assets/js/jquery.ui.widget.js"></script>
    <script src="/Content/fileupload/assets/js/jquery.iframe-transport.js"></script>
    <script src="/Content/fileupload/assets/js/jquery.fileupload.js"></script>
    <script src="/Content/fileupload/assets/js/script.js"></script>
    
    <!-- Social Media -->
    <script type="text/javascript" src='https://apis.google.com/js/plusone.js'></script>    <!-- Social Media -->

    @Scripts.Render("~/bundles/custom/js")
   
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            "use strict";
            $('#solblockjs').perfectScrollbar();
        });
    </script>
    <script type="text/javascript">
        $(window).load(function() {
            $('#recorderFlashContainer').css({ 'top': '-9999px', 'left': '-9999px' });
        });
    </script>
    <script type="text/javascript">
        $(document).click(function (event) {
            if ($(event.target).attr('data-ajax-update') === '#LeftContent') {
                window.lastElementClicked = event.target;
            }
        });
        $(document).ready(function() {
            setInterval(function () {
                if (window.lastElementClicked) {
                    $(window.lastElementClicked).click();
                }
                else {
                    $('#RecentlyAddedkeywordList').click();
                }
            }, 60*1000);
        });
    </script>
    <script type="text/javascript">
        function getPlayer(pid) {
            var obj = document.getElementById(pid);
            if (obj.doPlay) return obj;
            for (i = 0; i < obj.childNodes.length; i++) {
                var child = obj.childNodes[i];
                if (child.tagName == "EMBED") return child;
            }
        }

        function PlayCurrentItem(element) {
            var player = getPlayer("audio1");

            // Stop running instances
            player.doStop();
            $('.icon-pause').each(function () {
                $(this).removeClass('icon-pause').addClass('icon-play');
                $(this).attr('onclick', 'PlayCurrentItem(this);');
            });

            // Play this one
            $(element).removeClass('icon-play').addClass('icon-pause');
            $(element).attr('onclick', 'PauseCurrentItem(this);');
            player.play($(element).attr('data-url'));
        }

        function PauseCurrentItem(element) {
            var player = getPlayer("audio1");

            // Pause this one
            $(element).removeClass('icon-pause').addClass('icon-play');
            $(element).attr('onclick', 'PlayCurrentItem(this);');
            player.doStop();
        }

        // Test Functions
        function doPlay(fname) {
            var player = getPlayer("audio1");
            player.play(fname);
        }
        function doStop() {
            var player = getPlayer("audio1");
            player.doStop();
        }
    </script>
    <script type="text/javascript">
        $(document)
            .bind("ajaxSend", function () {
                $("#Loading").show();
            })
            .bind("ajaxComplete", function (param1, param2, param3, param4) {
                $("#Loading").hide();
                //var response = $(param2.responseText);
                //$('#' + response[0].id).hide('slow').show('slow');
                $('body').find('*').tooltip();
            })
            .bind('ajaxError', function () {
                $("#Loading").hide();
            });

        function AjaxCompleted(targetElementId) {
            $('#' + targetElementId).fadeOut('fast').slideDown('normal');
        }

        function RestoreOperationsContent() {
            $('textarea').wysihtml5();
            $('html,body').animate({ scrollTop: $('#divOperations').offset().top-100 }, 'slow');
            InitFileUpload();

            $('#BtnCreateContent').click(function (event) {
                if (fileUploadDataContext != null) {
                    event.preventDefault();
                    fileUploadDataContext
                        .submit()
                        .success(function (result, textStatus, jqXhr) {
                        })
                        .error(function (jqXhr, textStatus, errorThrown) {

                        })
                        .complete(function (result, textStatus, jqXhr) {
                            $('#divOperations').html(result.responseText);
                            $("#Loading").hide();
                            RestoreOperationsContent();
                        });
                }
            });
        }
    </script>
    <script type="text/javascript">
    //function RebootSoundManager() {
        //    soundManager.reboot();
        //    setTimeout(function () {
        //        soundManager.reboot();
        //    }, 1000);
        //}

        //// IE fix
        //function PlaySound(url) {
        //    document.all.sound.src = url;
        //}
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('body').find('*').tooltip();
        });
    </script>
    <script type="text/javascript">
    //$(document).ready(function () {
        //    soundManager.setup({
        //        url: '/Content/soundmanager/swf/'
        //    });
        //});
    </script>
    <script type="text/javascript">
        $(function () {
            $(document).ajaxError(function (e, xhr) {
                if (xhr.status == 403) {
                    location.href = "/Account/Login";
                }
            });
        });
    </script>
    <script type="text/javascript">
        $(function () {
            window.onerror = function (message, url, line) {
                //bootbox.alert('İşleminiz gerçekleştirilirken hata oluştu, lütfen tekrar deneyiniz!');
                return true;
            };
        });
    </script>
    
 <!--GOOGLE ANALYTICS CODE-->
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46477529-1', 'estudybase.com');
    ga('send', 'pageview');

</script>
<!--GOOGLE ANALYTICS CODE-->
</body>
</html>