EStudyBase/Models/Keyword.cs
using System;
using System.Collections.Generic;

namespace EStudyBase.Models
{
    public class Keyword
    {
        public Keyword()
        {
            KeywordTags = new List<KeywordTag>();
            Likes = new List<Like>();
            Contents = new List<Content>();
        }

        public int KeywordId { get; set; }
        public string Definition { get; set; }
        public string Synonym { get; set; }
        public string Antonym { get; set; }
        public int LanguageId { get; set; }
        public int CreateUserId { get; set; }
        public int? ModifyUserId { get; set; }
        public bool Approved { get; set; }
        public int Order { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public virtual ICollection<KeywordTag> KeywordTags { get; set; }
        public virtual UserProfile CreateUser { get; set; }
        public virtual Language Language { get; set; }
        public virtual UserProfile ModifyUser { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
    }
}

EStudyBase/Models/Like.cs
using System;

namespace EStudyBase.Models
{
    public class Like
    {
        public int KeywordId { get; set; }
        public int SourceId { get; set; }
        public int LikeUserId { get; set; }
        public bool Status { get; set; }
        public int SourceTypeId { get; set; }
        public DateTime CreateDate { get; set; }
        public virtual Keyword Keyword { get; set; }
        public virtual LikeSourceType LikeSourceType { get; set; }
        public virtual UserProfile CreateUser { get; set; }
    }
}

EStudyBase/Models/Tag.cs
using System;
using System.Collections.Generic;

namespace EStudyBase.Models
{
    public class Tag
    {
        public Tag()
        {
            KeywordTags = new List<KeywordTag>();
        }

        public int TagId { get; set; }
        public int? TagParentId { get; set; }
        public string Definition { get; set; }
        public int LanguageId { get; set; }
        public int CreateUserId { get; set; }
        public int? ModifyUserId { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public virtual ICollection<KeywordTag> KeywordTags { get; set; }
        public virtual Language Language { get; set; }
        public virtual UserProfile CreateUser { get; set; }
        public virtual UserProfile ModifyUser { get; set; }
    }
}

EStudyBase/ViewModels/ContentListViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class ContentListViewModel
    {
        public int? KeywordId { get; set; }
        public string Term { get; set; }
        public int? UserId { get; set; }
        public int TotalCount { get; set; }
        public int CurrentPage { get; set; }
        public int FirstPage { get; set; }
        public int LastPage { get; set; }
        public IEnumerable<SelectListItem> Pages { get; set; }
        public ICollection<Content> Contents { get; set; }
    }
}

EStudyBase/ViewModels/KeywordViewModel.cs
using System;
﻿using System.Collections.Generic;
﻿using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
﻿using System.Web.Mvc;
﻿using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class KeywordViewModel
    {
        private string _definition;
        public int? KeywordId { get; set; }

        [Required(ErrorMessage = " ")]
        [DisplayName("Başlık")]
        [StringLength(100,ErrorMessage = "Başlık 100 karakteri aşamaz.")]
        public string Definition
        {
            get
            {
                //return
                //    string.IsNullOrWhiteSpace(_definition)
                //        ? string.Empty
                //        : _definition.ToLower()
                //                     .Replace("?", "")
                //                     .Replace("mı", "")
                //                     .Replace("mi", "")
                //                     .Replace("mu", "")
                //                     .Replace("mü", "")
                //                     .Trim();
                return _definition;
            }
            set { _definition = value; }
        }

        [Display(Name = "Dil")]
        public int LanguageId { get; set; }
        public IEnumerable<SelectListItem> Languages { get; set; }

        [DisplayName("#Etiket")]
        public List<Tag> Tags { get; set; }
        [Required(ErrorMessage = " ")]
        public Int32[] SelectedTags { get; set; }

        [DisplayName("Başlık eş anlamı")]
        public string Synonym { get; set; }

        [DisplayName("Başlık zıt anlamı")]
        public string Antonym { get; set; }

        [Required(ErrorMessage = " ")]
        [DisplayName("Başlık sırası")]
        public int Order { get; set; }

        [DisplayName("Onayla")]
        public bool Approved { get; set; }

        public int LikeCount { get; set; }

        public int DislikeCount { get; set; }
    }
}

EStudyBase/ViewModels/LikeViewModel.cs
namespace EStudyBase.ViewModels
{
    public class LikeViewModel
    {
        public int KeywordId { get; set; }
        public int SourceId { get; set; }
        public int SourceTypeId { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
        public bool AlreadyVoted { get; set; }
    }
}

EStudyBase/ViewModels/SearchViewModel.cs
using System.Collections.Generic;
using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class SearchViewModel
    {
        public int KeywordId { get; set; }
        public string Definition { get; set; }
        public string Synonym { get; set; }
        public string Antonym { get; set; }
        public int Order { get; set; }
        public UserProfile CreateUser { get; set; }
        public ICollection<Content> Contents { get; set; }
        public ICollection<Keyword> RelatedKeywords { get; set; }
        public int PageNumber { get; set; }        
        public int PageSize { get; set; }
        public int TotalPageNumber { get; set; }
        public int TotalRecords { get; set; }

        public KeywordSearchCriteriaViewModel SearchCriteria { get; set; }
    }
}

EStudyBase/ViewModels/UserPortfolioViewModel.cs
using System.Collections.Generic;
using EStudyBase.Models;

namespace EStudyBase.ViewModels
{
    public class UserPortfolioViewModel
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public ICollection<Keyword> Keywords { get; set; }
        public ICollection<Content> Contents { get; set; }
    }
}

EStudyBase/Controllers/KeywordController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using EStudyBase.Attributes;
using EStudyBase.Filters;
using EStudyBase.Mailers;
using EStudyBase.Models;
using EStudyBase.ViewModels;
using WebMatrix.WebData;

namespace EStudyBase.Controllers
{
    [InitializeSimpleMembership]
    public class KeywordController : Controller
    {
        private readonly EStudyBaseContext _context = new EStudyBaseContext();

        private Keyword GetMostPopularKeyword() {
            try {
                var keyword =
                    _context.Database.SqlQuery<Keyword>("SELECT * FROM dbo.GetMostPopularKeyword()").FirstOrDefault();

                return keyword;
            } catch(Exception exception) {
                throw new Exception("Error in KeywordController.GetMostPopularKeyword", exception);
            }
        }

        //[OutputCache(Duration = 3600, VaryByParam = "none")]
        public ActionResult GetTotalKeywordCount() {
            try {
                var totalKeywordCount = _context.Keywords.Count();
                var totalContentCount = _context.Contents.Count();

                var content = string.Format(@"Toplam <b>{0}</b> başlık ve <b>{1}</b> içerik ile her gün büyüyen sözlük!",
                                            totalKeywordCount, totalContentCount);
                return Content(content);
            } catch(Exception exception) {
                throw new Exception("Error in KeywordController.GetTotalKeywordCount", exception);
            }
        }

        public ActionResult Search(KeywordSearchCriteriaViewModel searchCriteria) {
            try {
                //...
                // Redirect to most popular keyword
                if(searchCriteria.KeywordId == null && string.IsNullOrWhiteSpace(searchCriteria.Term)) {
                    var keyword = GetMostPopularKeyword();
                    searchCriteria.KeywordId = keyword.KeywordId;
                }


                SearchViewModel searchViewModel = null;

                //...
                // If request type is post try to get term from form collection
                if(HttpContext.Request.RequestType == "POST") {
                    searchCriteria.Term = HttpContext.Request.Form["Term"];
                }

                //...
                // Search logic
                if(searchCriteria.KeywordId.HasValue && searchCriteria.KeywordId > 0) {
                    searchViewModel = _context
                        .Keywords
                        .Include(p => p.Contents)
                        .Include(p => p.Contents.Select(q => q.ContentCategory))
                        .Include(p => p.CreateUser)
                        .Where(p => p.KeywordId == searchCriteria.KeywordId && p.Approved)
                        .Select(p => new SearchViewModel {
                            KeywordId = p.KeywordId,
                            Definition = p.Definition,
                            Synonym = p.Synonym,
                            Antonym = p.Antonym,
                            Order = p.Order,
                            CreateUser = p.CreateUser
                        })
                        .FirstOrDefault();
                } else if(!string.IsNullOrWhiteSpace(searchCriteria.Term)) {
                    searchViewModel = _context
                        .Keywords
                        .Include(p => p.Contents)
                        .Include(p => p.Contents.Select(q => q.ContentCategory))
                        .Include(p => p.CreateUser)
                        .Where(p => p.Definition.ToLower().Equals(searchCriteria.Term.ToLower()) && p.Approved)
                        .Select(p => new SearchViewModel {
                            KeywordId = p.KeywordId,
                            Definition = p.Definition,
                            Synonym = p.Synonym,
                            Antonym = p.Antonym,
                            Order = p.Order,
                            CreateUser = p.CreateUser
                        })
                        .FirstOrDefault();
                }

                //...
                // No keyword found for this search
                // Suggest related keywords
                if(searchViewModel == null) {
                    DbSqlQuery<Keyword> relatedKeywords = _context.Keywords.SqlQuery(
                        string.Format(@"SELECT TOP 5 * FROM Keyword
                                        ORDER BY dbo.LevenshteinSearchAlgorithm('{0}',Definition)",
                            ViewBag.Term));
                    searchViewModel = new SearchViewModel {
                        RelatedKeywords = relatedKeywords.ToList()
                    };
                }

                searchCriteria.Term = searchViewModel.Definition;
                searchViewModel.SearchCriteria = searchCriteria;

                return View(searchViewModel);
            } catch(Exception exception) {
                throw new Exception("Error in KeywordController.Search", exception);
            }
        }

        public ActionResult SocialNetwork(int contentId = 0) {
            var contentViewModel =
                _context.Contents
                    .Where(p => p.ContentId == contentId)
                    .Select(p => new ContentViewModel {
                        ContentId = p.ContentId,
                        KeywordId = p.KeywordId
                    })
                    .FirstOrDefault();
            return View("SocialNetwork", contentViewModel);
        }

        public ActionResult GetKeywordTagList(int? keywordId = null) {
            if(keywordId == null) {
                return PartialView("_KeywordTagList");
            }

            var tagList = _context
                .KeywordTags
                .Include(p => p.Tag)
                .Where(p => p.KeywordId == keywordId)
                .ToList();

            return PartialView("_KeywordTagList", tagList);
        }

        public ActionResult GetContentList(ContentSearchCriteriaViewModel searchCriteria) {
            if(searchCriteria == null)
                throw new ArgumentNullException("searchCriteria");

            if(searchCriteria.PageDirection != null) {
                if(searchCriteria.PageDirection.Equals("Next")) {
                    searchCriteria.CurrentPage++;
                } else {
                    searchCriteria.CurrentPage--;
                }
            }

            //...
            // Pages dropdown list
            var totalContentCount = _context.Contents
                .Count(k => (k.KeywordId == searchCriteria.KeywordId || searchCriteria.KeywordId == null)
                            && (k.CreateUserId == searchCriteria.UserId || searchCriteria.UserId  == null)
                            && (k.ContentId == searchCriteria.ContentId || searchCriteria.ContentId == null)
                            && k.Approved);


            IDictionary<int, int> pages = new Dictionary<int, int>();
            for(int i = 1; i <= (totalContentCount / 10) + 1; i++) {
                pages.Add(new KeyValuePair<int, int>(i, i));
            }

            var skip = (searchCriteria.CurrentPage - 1) * 10;


            //...
            // Get content list page
            var contentsQuery = _context.Contents
                .Where(k => (k.KeywordId == searchCriteria.KeywordId || searchCriteria.KeywordId == null)
                            && (k.CreateUserId == searchCriteria.UserId || searchCriteria.UserId == null)
                            && (k.ContentId == searchCriteria.ContentId || searchCriteria.ContentId == null)
                            && k.Approved);

            // Sort by language
            contentsQuery = searchCriteria.LanguageId == 1
                ? contentsQuery
                    .OrderBy(k => k.LanguageId)
                    .ThenBy(k => k.ContentType)
                    .ThenByDescending(k => k.CreateDate)
                    .Skip(skip)
                    .Take(10)
                : contentsQuery
                    .OrderByDescending(k => k.LanguageId)
                    .ThenBy(k => k.ContentType)
                    .ThenByDescending(k => k.CreateDate)
                    .Skip(skip)
                    .Take(10);

            //...
            // Get current keyword
            var keyword = _context.Keywords.FirstOrDefault(p => p.KeywordId == searchCriteria.KeywordId);

            //...
            // Return view model
            var contentListViewModel = new ContentListViewModel {
                KeywordId = searchCriteria.KeywordId,
                UserId = searchCriteria.UserId,
                Term = keyword == null ? string.Empty : keyword.Definition,
                CurrentPage = searchCriteria.CurrentPage,
                FirstPage = 1,
                LastPage = pages.Count,
                Pages = new SelectList(pages, "Key", "Value", searchCriteria.CurrentPage),
                TotalCount = totalContentCount,
                Contents = contentsQuery.ToList(),
            };

            return PartialView("_ContentList", contentListViewModel);
        }

        public ActionResult SearchSuggestions(string term = null) {
            if(string.IsNullOrWhiteSpace(term)) {
                return null;
            }

            try {
                var suggestionList =
                    _context.Database.SqlQuery<string>(string.Format(@"SELECT * FROM dbo.GetKeywordSuggestionList('{0}')", term)).ToList();

                return Json(suggestionList, JsonRequestBehavior.AllowGet);
            } catch(Exception exception) {
                throw new Exception("Error in KeywordController.SearchSuggestions", exception);
            }
        }

        //[OutputCache(Duration = 3600, VaryByParam = "none")]
        public PartialViewResult GetTags() {
            try {

EStudyBase/Views/Keyword/Search.cshtml
@using EStudyBase.ViewModels
@model SearchViewModel

@{
    ViewBag.Title = Model != null ? Model.Definition : "EStudyBase";
}

@if(Model != null && Model.KeywordId > 0) {
    <div class="mainheader">
        <div class="sola responsive2" style="width: 465px; margin-top: 5px; min-height: 92px;">
            <h2>@Html.ActionLink(Model.SearchCriteria.Term, "Search", "Keyword", new { Term = Model.SearchCriteria.Term }, null)</h2>
            @if(Model.Order > 0) {
                <a class="sozluk-sirasi" href="javascript:;" title="Sözlük Sırası">@Model.Order<span style="font-size: 12px;">. sırada!</span></a>
            }
            <a class="seslendir" href="javascript:;" title="Telaffuz"></a><br />
            @{
    Html.RenderAction("GetKeywordTagList", "Keyword", new { keywordId = Model.KeywordId });
            }
            <br />
            @if(!string.IsNullOrWhiteSpace(Model.Synonym)) {
                <span class="eszit">eş anlam : </span>
                <span style="font-size: 11px; color: #418f03; margin-right: 20px;">

                    <span>@Html.ActionLink(Model.Synonym, "Search", "Keyword", new { Term = Model.Synonym }, null)</span>
                </span>

            }
            @if(!string.IsNullOrWhiteSpace(Model.Antonym)) {
                <span class="eszit">zıt anlam : </span>
                <span style="font-size: 11px; color: #418f03;">

                    <span>@Html.ActionLink(Model.Antonym, "Search", "Keyword", new { Term = Model.Antonym }, null)</span>
                </span>

            }
            <div>
                @Html.ActionLink("Türkçe", "Search", "Keyword", new { Term = Model.SearchCriteria.Term, LanguageId = 1 }, null)
                @Html.ActionLink("English", "Search", "Keyword", new { Term = Model.SearchCriteria.Term, LanguageId = 2 }, null)
            </div>
        </div>
        <div class="saga" style="margin-top: 35px;">
            @Ajax.ActionLink("yeni başlık ekle", "CreateKeyword", "Content", new { keywordId = Model.KeywordId }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divOperations", OnSuccess = "RestoreOperationsContent" }, new { @class = "yesil-buton", style = "margin-right:20px;" })
            @Ajax.ActionLink("yeni tanım ekle", "CreateContent", "Content", new { keywordId = Model.KeywordId }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divOperations", OnSuccess = "RestoreOperationsContent" }, new { @class = "yesil-buton", style = "margin-right:20px;" })
            @Ajax.ActionLink("ses kaydı ekle", "CreateRecord", "Content", new { keywordId = Model.KeywordId }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divOperations", OnSuccess = "RestoreOperationsContent" }, new { @class = "gri-buton" })
        </div>
    </div>
    <div class="clear"></div>

    <!-- Contents -->
    <div id="tableSearchResults">
        @{
            Html.RenderAction("GetContentList", "Keyword", 
                new {
                    KeywordId = Model.KeywordId, 
                    ContentId = Model.SearchCriteria.ContentId, 
                    LanguageId = Model.SearchCriteria.LanguageId
                });
        }
    </div>
    <!-- Contents -->
} else {
    Html.RenderPartial("_RelatedKeywords", Model);
}

EStudyBase/Views/Keyword/SocialNetwork.cshtml
@model EStudyBase.ViewModels.ContentViewModel 

<br />
<br />
@{
    Html.RenderAction("GetContentList", "Keyword", new { keywordId = Model.KeywordId, contentId = Model.ContentId });
}

EStudyBase/Views/Keyword/UserPortfolio.cshtml
@model EStudyBase.ViewModels.UserPortfolioViewModel

@{
    ViewBag.Title = Model != null ? Model.UserName : "Anonym";
}

@if (Model != null)
{

    
    
    
    
    
    <div class="mainheader">
        <div class="sola responsive2" style="width: 465px; margin-top: 5px; min-height: 90px;">
            <h2>@Html.ActionLink(Model.UserName, "UserPortfolio", "Keyword", new { userName = Model.UserName }, null)</h2>
            <br />
            @if (Model.Keywords != null && Model.Keywords.Any())
            {
                <div>
                    @foreach (var keyword in Model.Keywords)
                    {
                        <span><a class="tagtext" href="/Keyword/Search?Term=@keyword.Definition" title="@keyword.Definition">@keyword.Definition</a></span>
                    }
                </div>
            }
        </div>
        <div class="saga" style="margin-top: 35px;">
            @Html.ActionLink("mesaj gönder", "EmailBox", "Email", new { userName = Model.UserName }, new { target = "_blank", @class = "yesil-buton saga" })
        </div>
    </div>
    <div class="clear"></div>
    
    <!-- Contents -->
            if (Model.Contents != null && Model.Contents.Any())
            {
    <div id="tableSearchResults">
        @{
                Html.RenderAction("GetContentList", "Keyword", new { userId = Model.UserId });
        }
    </div>
            }
    <!-- Contents -->
}

EStudyBase/Views/Keyword/_KeywordList.cshtml
@using EStudyBase.ViewModels
@model IEnumerable<KeywordViewModel>
@{
    string lastPage = Convert.ToString(ViewBag.LastPage);
}

<h3 class="solblockbaslik">@ViewBag.SectionHeader</h3>
<div class="solblockmenu">
    @if(Model.Any()) {
        if(((SelectList)ViewBag.Pages).Count() > 1) {
            <div class="pagination" style="margin: 0;">
                <ul>
                    <li class="prev">
                        @Ajax.ActionLink("<<", "GetKeywordList", "Keyword", new KeywordSearchCriteriaViewModel {
                       OperationType = ViewBag.OperationType,
                       TagId = ViewBag.TagId,
                       CurrentPage = ViewBag.FirstPage
                   }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "LeftContent", InsertionMode = InsertionMode.Replace, OnComplete = "AjaxCompleted('LeftContent')" })
                    </li>

                    @if(ViewBag.CurrentPage > 1) {
                        <li class="prev">
                            @Ajax.ActionLink("<", "GetKeywordList", "Keyword", new KeywordSearchCriteriaViewModel {
                           OperationType = ViewBag.OperationType,
                           TagId = ViewBag.TagId,
                           CurrentPage = ViewBag.CurrentPage,
                           PageDirection = "Previous"
                       }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "LeftContent", InsertionMode = InsertionMode.Replace, OnComplete = "AjaxCompleted('LeftContent')" })
                        </li>
                    }
                    <li class="prev">
                        @Html.DropDownList("KeywordPageList", (SelectList)ViewBag.Pages, new { style = "width:80px;margin-top:8px;" }) /
                        @Ajax.ActionLink(lastPage, "GetKeywordList", "Keyword", new KeywordSearchCriteriaViewModel {
                            OperationType = ViewBag.OperationType,
                            TagId = ViewBag.TagId,
                            CurrentPage = ViewBag.LastPage
                        }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "LeftContent", InsertionMode = InsertionMode.Replace, OnComplete = "AjaxCompleted('LeftContent')" })
                    </li>
                    @if(Model.Count() == 20) {
                        <li class="next">
                            @Ajax.ActionLink(">", "GetKeywordList", "Keyword", new KeywordSearchCriteriaViewModel {
                           OperationType = ViewBag.OperationType,
                           TagId = ViewBag.TagId,
                           CurrentPage = ViewBag.CurrentPage,
                           PageDirection = "Next"
                       }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "LeftContent", InsertionMode = InsertionMode.Replace, OnComplete = "AjaxCompleted('LeftContent')" })
                        </li>
                    }
                    <li class="prev">
                        @Ajax.ActionLink(">>", "GetKeywordList", "Keyword", new KeywordSearchCriteriaViewModel {
                       OperationType = ViewBag.OperationType,
                       TagId = ViewBag.TagId,
                       CurrentPage = ViewBag.LastPage
                   }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "LeftContent", InsertionMode = InsertionMode.Replace, OnComplete = "AjaxCompleted('LeftContent')" })
                    </li>
                </ul>
        </div>
        }
    } else {
        <div class="alert alert-error">Başlık bulunamadı!</div>
    }
    <ul style="margin:0;">
        @foreach(var keywordViewModel in Model) {
            <li>
                <a href="/Keyword/Search?Term=@keywordViewModel.Definition" title="@keywordViewModel.Definition">@keywordViewModel.Definition</a>
            </li>
        }
    </ul>



    <script type="text/javascript">
        $(function () {
            $('#KeywordPageList').change(function () {
                $.get('/Keyword/GetKeywordList/?currentPage=' + $(this).val() + '&pageDirection=none&operationType=@ViewBag.OperationType' + '&tagId=@ViewBag.TagId', {},
                    function (data) {
                        $('#LeftContent').html(data).fadeOut('fast').slideDown('slow');;
                    }
                );
            });
        });
    </script>

EStudyBase/Views/Keyword/_KeywordTagList.cshtml
@using EStudyBase.ViewModels
@model IEnumerable<EStudyBase.Models.KeywordTag>
@if (Model != null && Model.Any())
{
    <b class="tagtext">Etiketler</b>    
    foreach (var keywordTag in Model)
    {
        <span>

            @Ajax.ActionLink("#" + keywordTag.Tag.Definition, "GetKeywordList", "Keyword",
                              new KeywordSearchCriteriaViewModel {
                                  OperationType = "GetKeywordListByTag", 
                                  TagId = keywordTag.TagId
                              },
                             new AjaxOptions
                                 {
                                     HttpMethod = "GET",
                                     UpdateTargetId = "LeftContent",
                                     InsertionMode = InsertionMode.Replace,
                                     OnComplete = "AjaxCompleted('LeftContent')"
                                 }, new {@class = "tagtext", title = keywordTag.Tag.Definition})
        </span>

    }
}

EStudyBase/Views/Keyword/_Like.cshtml
@model EStudyBase.ViewModels.LikeViewModel

<div id="divLike_@Model.SourceId">

    @Ajax.ActionLink(" ", "LikeDislike", "Keyword",
                     new { keywordId = Model.KeywordId, sourceId = Model.SourceId, sourceTypeId = Model.SourceTypeId, status = 1 },
                     new AjaxOptions
                         {
                             UpdateTargetId = "divLike_" + Model.SourceId,
                             InsertionMode = InsertionMode.Replace,
                             OnComplete = "AjaxCompleted('divLike_" + Model.SourceId + "')"
                         }, new { @class = " icon-thumbs-up", title = "Beğen" })
    @Model.LikeCount

    @Ajax.ActionLink(" ", "LikeDislike", "Keyword",
                     new { keywordId = Model.KeywordId, sourceId = Model.SourceId, sourceTypeId = Model.SourceTypeId, status = 0 },
                     new AjaxOptions
                         {
                             UpdateTargetId = "divLike_" + Model.SourceId,
                             InsertionMode = InsertionMode.Replace,
                             OnComplete = "AjaxCompleted('divLike_" + Model.SourceId + "')"
                         }, new { @class = "icon-thumbs-down", title = "Beğenme" })
    @Model.DislikeCount

    <img class="icon-share" onclick="LoadExternalResources(@Model.SourceId)" style="cursor: pointer;" title="Paylaş"/>
    <div id="divSocialNetworks_@Model.SourceId"  class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="divSocialNetworksHeader">Paylaş</h4>
                </div>
                <div class="modal-body">
                    <div id="divSocialNetworksContent_@Model.SourceId">
                    </div>
                    <!--facebook-->
                    <div class="sola" id="facebook_@Model.SourceId" style="margin-right: 6px;">
                    </div>
                    <!--facebook_bitti-->
                    <!--googleplus-->
                    <div class="sola" id="google_@Model.SourceId" style="margin-right: 5px;"></div>
                    <!--googleplus_bitti-->
                    <!--twitter-->
                    <div class="sola" id="twitter_@Model.SourceId">
                    </div>
                    <!--twitter-bitti-->
                </div>
            </div>
        </div>
    </div>
    @Ajax.ActionLink(" ", "Complain", "Keyword",
                     new { contentId = Model.SourceId },
                     new AjaxOptions(), new { @class = "icon-flag", title = "Şikayet Et" })
    
</div>

EStudyBase/Views/Keyword/_Tags.cshtml
@using EStudyBase.ViewModels
@model IEnumerable<EStudyBase.Models.Tag>

@{
    int index = 0;
}
@foreach (var tagParent in Model)
{
    index++;
    if (tagParent.TagParentId == null)
    {
    <li class="dropdown pull-right">
        <a id="drop_@index" role="button" data-toggle="dropdown" href="#">@tagParent.Definition<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="drop_@index">
            @foreach (var tagSub in Model)
            {
                if (tagSub.TagParentId == tagParent.TagId)
                {
                <li>
                    @Ajax.ActionLink("#"+tagSub.Definition, "GetKeywordList", "Keyword",
                             new KeywordSearchCriteriaViewModel {
                                 OperationType = "GetKeywordListByTag",
                                 TagId = tagSub.TagId
                             },
                        new AjaxOptions
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "LeftContent",
                                InsertionMode = InsertionMode.Replace,
                                OnComplete = "AjaxCompleted('LeftContent')"
                            })
                </li>
                }

            }
        </ul>
    </li>
    }
}